import{createRequire}from'node:module';import{writeFile}from'node:fs/promises';const{chromium}=createRequire(import.meta.url)('playwright');await import('../scripts/serve.mjs');const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});const results=[],errors=[];
const settle=async page=>page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));
for(const width of[360,1440]){
 const page=await browser.newPage({viewport:{width,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});await page.goto('http://127.0.0.1:4321/es/');await settle(page);await page.screenshot({animations:'disabled',path:`verification/refined-dark-${width}.jpg`});
 await page.locator('.theme-toggle').click();await page.waitForFunction(()=>getComputedStyle(document.body).backgroundColor==='rgb(232, 222, 210)');await settle(page);await page.screenshot({animations:'disabled',path:`verification/refined-light-${width}.jpg`});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow');if(await page.locator('.theme-toggle').getAttribute('aria-pressed')!=='true')throw Error('Theme state');
 await page.evaluate(()=>window.languageMarker=123);
 for(const lang of['en','es','en','es','en']){await page.locator(`.languages a[lang=${lang}]`).click();await page.waitForFunction(lang=>document.documentElement.lang===lang,lang);await settle(page);if(!await page.evaluate(()=>window.languageMarker===123))throw Error('Reload');if(await page.locator('h1').textContent()==='')throw Error('Missing translation');}
 await page.goBack();await page.waitForFunction(()=>document.documentElement.lang==='es');await settle(page);await page.goForward();await page.waitForFunction(()=>document.documentElement.lang==='en');await settle(page);
 await page.locator('.piece-image[data-open="4"]').click();await page.locator('#detail-image').evaluate(i=>i.decode());await page.keyboard.press('ArrowRight');if(await page.locator('[data-view="1"]').getAttribute('aria-pressed')!=='true')throw Error('Duplicate keyboard event');await page.keyboard.press('Escape');
 await page.reload();if(await page.evaluate(()=>document.documentElement.dataset.theme)!=='light')throw Error('Reload persistence');if(await page.locator('.theme-toggle').getAttribute('aria-label')!=='Switch to dark mode')throw Error('Translated theme label');
 await page.locator('#contact').scrollIntoViewIfNeeded();await settle(page);await page.screenshot({animations:'disabled',path:`verification/refined-contact-${width}.jpg`});
 results.push({width,themePersistence:'pass',normalMotion:'enabled',noReloadLanguage:'pass',repeatedLanguageSwitches:5,historyBackForward:'pass',eventCleanup:'pass',themeAccessibleState:'pass',horizontalOverflow:false});await page.close();console.log('PASS controls',width);
}
await browser.close();if(errors.length)throw Error(JSON.stringify(errors));await writeFile('verification/controls-results.json',JSON.stringify({results,errors},null,2));process.exit();
