import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
const catalog=JSON.parse(await readFile('src/catalog.json','utf8'));
const locales=JSON.parse(await readFile('src/locales.json','utf8'));
const ig='https://www.instagram.com/luzcelestia.ni/';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15M13 5l7 7-7 7"/></svg>';
const instagram='<svg class="ig-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/></svg>';
const sun='<svg class="sun" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg>';
const moon='<svg class="moon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.5A9 9 0 0 1 8.5 4a9 9 0 1 0 11.5 11.5Z"/><path d="m17 3 .5 1.5L19 5l-1.5.5L17 7l-.5-1.5L15 5l1.5-.5Z"/></svg>';
const motif='<svg viewBox="0 0 48 58" aria-hidden="true"><path d="M20 3h9v13h13v9H29v28h-9V25H7v-9h13z"/><path d="M24 31c-9-8-12 2 0 9 12-7 9-17 0-9z"/></svg>';
function page(lang){const t=locales[lang];
const item=(i,variant='')=>{const p=catalog[i],c=p[lang];return `<article class="piece ${variant}"><button class="piece-image" data-open="${i}" aria-label="${esc(t.view+': '+c.name)}"><img src="/assets/campaign/${p.id}.webp" alt="${esc(c.name)}" loading="lazy" width="1024" height="1280"><span class="explore">${esc(t.view)} ${arrow}</span></button><div class="piece-caption"><div><p class="state">${i===0?t.available:t.preorder}</p><h3><button data-open="${i}">${esc(c.name)}</button></h3></div><span class="price">US$${p.price}</span></div></article>`};
return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Luz Celestia — ${t.collection}</title><meta name="description" content="${esc(t.heroText)}"><meta name="theme-color" content="#112833"><meta property="og:title" content="Luz Celestia"><meta property="og:description" content="${esc(t.heroText)}"><meta property="og:image" content="https://ceslestiani.vercel.app/assets/campaign/hero.webp"><link rel="canonical" href="https://ceslestiani.vercel.app/${lang}/"><link rel="alternate" hreflang="en" href="https://ceslestiani.vercel.app/en/"><link rel="alternate" hreflang="es" href="https://ceslestiani.vercel.app/es/"><link rel="icon" href="/assets/logo/favicon.svg"><script>try{document.documentElement.dataset.theme=localStorage.getItem("lc_theme")==="light"?"light":"dark"}catch{document.documentElement.dataset.theme="dark"}</script><link rel="stylesheet" href="/style.css"></head><body><div class="reading-progress" aria-hidden="true"></div><svg class="logo-filter" aria-hidden="true" width="0" height="0"><defs><filter id="logo-alpha" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 -1 -1 -1 0 3"/><feComponentTransfer result="keyed"><feFuncA type="discrete" tableValues="0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1"/></feComponentTransfer><feComposite in="keyed" in2="SourceGraphic" operator="in"/></filter></defs></svg>
<a class="skip" href="#collection">${t.skip}</a>
<header id="top"><a class="brand" href="#top"><svg class="brand-logo" viewBox="0 0 1420 560" role="img" aria-label="Luz Celestia"><image href="/assets/logo/wordmark.png" width="1420" height="560" filter="url(#logo-alpha)"/></svg></a><nav aria-label="${t.collection}"><a href="#collection">${t.collection}</a><a href="#contact">${t.contact}</a></nav><div class="header-controls"><button class="theme-toggle" type="button" aria-label="${t.themeLight}" title="${t.themeLight}" aria-pressed="false"><span class="theme-orbit">${sun}${moon}</span></button><div class="languages" aria-label="${t.lang}"><a href="/en/" lang="en" ${lang==='en'?'aria-current="page"':''}aria-label="English (United States)" title="English"><img class="flag" src="/assets/flags/us.svg" alt="">EN</a><a href="/es/" lang="es" ${lang==='es'?'aria-current="page"':''}aria-label="Español (España)" title="Español"><img class="flag" src="/assets/flags/es.svg" alt="">ES</a></div></div></header>
<main><section class="hero"><img class="hero-photo" src="/assets/campaign/hero.webp" alt="${esc(catalog[4][lang].description)}" width="1536" height="1024" fetchpriority="high"><div class="hero-copy"><p class="eyebrow">${t.eyebrow}</p><h1>${t.heroA}<br><em>${t.heroB}</em></h1><p class="hero-text">${t.heroText}</p><a class="button" href="#collection">${t.discover} ${arrow}</a></div><button class="hero-caption" data-open="4">${t.heroLink} ${arrow}</button><span class="hero-mark">${motif}</span></section>
<section class="collection" id="collection"><div class="collection-intro"><span class="eyebrow">Luz Celestia / ${t.collection}</span><h2>${t.intro}</h2><p>${t.introText}</p></div>
<div class="opening-spread">${item(0,'opening-piece')}<aside class="opening-note">${motif}<p>${catalog[0][lang].detail}</p><span>US$2 · ${t.available}</span><button class="text-link" data-open="0">${t.view} ${arrow}</button></aside></div>
<div class="chapter"><div class="chapter-title"><h2>${t.chapterA}</h2><p>${t.chapterAText}</p></div><div class="cross-spread">${item(1)}${item(2,'offset')}</div></div>
<div class="shell-spread"><div class="shell-copy">${motif}<h2>${t.chapterB}</h2><p>${t.chapterBText}</p><button class="text-link" data-open="3">${t.view} ${arrow}</button></div>${item(3,'shell-piece')}</div>
<div class="chapter last-chapter"><div class="chapter-title"><h2>${t.chapterC}</h2><p>${t.chapterCText}</p></div><div class="duo-spread">${item(4)}${item(5)}</div></div></section>
<section class="contact" id="contact"><div class="contact-photo"><img src="/assets/campaign/heart-close-hd.webp" alt="${esc(catalog[2][lang].detail)}" loading="lazy" width="900" height="900"></div><div class="contact-copy">${motif}<h2>${t.closing}</h2><p>${t.closingText}</p><a class="button instagram-button" href="${ig}" target="_blank" rel="noopener noreferrer">${instagram}<span class="ig-label"><strong>${t.closingButton}</strong><small>@luzcelestia.ni</small></span>${arrow}</a></div></section></main>
<footer><svg class="brand-logo" viewBox="0 0 1420 560" role="img" aria-label="Luz Celestia"><image href="/assets/logo/wordmark.png" width="1420" height="560" filter="url(#logo-alpha)"/></svg><p>${t.footer}</p><a href="#top">${t.top} ↑</a></footer>
<dialog id="detail" aria-labelledby="detail-name"><button class="close" aria-label="${t.close}">×</button><div class="detail-layout"><div class="gallery" aria-label="${t.gallery}"><div class="gallery-stage"><button class="zoom" aria-label="${t.zoom}"><img id="detail-image" alt=""></button><button class="gallery-arrow previous" aria-label="${t.previous}">←</button><button class="gallery-arrow next" aria-label="${t.next}">→</button></div><div class="gallery-status"><span class="gallery-view-label"></span><span class="gallery-count" aria-hidden="true">01 / 03</span></div><div class="gallery-tabs">${['campaign','detail','lifestyle'].map((key,i)=>`<button data-view="${i}" aria-pressed="${i===0}">${t[key]}</button>`).join('')}</div><p class="gallery-hint">${t.swipe}</p><details class="original-reference"><summary>${t.original}<span aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg></span></summary><img id="original-image" alt="" loading="lazy"></details></div><div class="detail-copy"><p class="eyebrow">Luz Celestia / ${t.collection}</p><div class="detail-meta"><span id="detail-state"></span><strong id="detail-price"></strong></div><h2 id="detail-name"></h2><p id="detail-description"></p><p class="detail-focus" id="detail-focus"></p><p class="order-note" id="order-note"></p><a class="button instagram-button" href="${ig}" target="_blank" rel="noopener noreferrer">${instagram}<span class="ig-label"><strong>${t.order}</strong><small>Instagram · @luzcelestia.ni</small></span>${arrow}</a><button type="button" class="copy-name text-link">${t.copy} ${arrow}</button><span class="copy-status" role="status" aria-live="polite"></span><p class="photo-note">${t.note}</p></div></div></dialog>
<script type="application/json" id="site-data">${JSON.stringify({lang,t,catalog})}</script><script src="/app.js" defer></script></body></html>`}
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('assets','dist/assets',{recursive:true});for(const f of ['style.css','app.js'])await cp('src/'+f,'dist/'+f);
for(const lang of ['en','es']){await mkdir('dist/'+lang,{recursive:true});await writeFile('dist/'+lang+'/index.html',page(lang));}
await writeFile('dist/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Luz Celestia</title><script>let l='en';try{l=localStorage.getItem('lc_lang')==='es'?'es':'en'}catch{}location.replace('/'+l+'/')</script><a href="/en/">English</a> · <a href="/es/">Español</a></html>`);
await writeFile('dist/robots.txt','User-agent: *\nAllow: /\nSitemap: https://ceslestiani.vercel.app/sitemap.xml\n');await writeFile('dist/sitemap.xml','<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://ceslestiani.vercel.app/en/</loc></url><url><loc>https://ceslestiani.vercel.app/es/</loc></url></urlset>');console.log('Built English and Spanish boutique in dist/');
